name: Unit Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: xcodebuild -project CombineDemo.xcodeproj -scheme CombineDemoTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' test | xcpretty
